### ISSUE TITLE
Upgrade Jersey and enable tests

### ISSUE THREAD

**Issue by f4lco** [gretty-gradle-plugin/gretty#163]
#159 disabled tests for Jersey. The API project has been jakarta-ified, but the Jersey implementation was not ready apparently. After a new Jersey release, we must upgrade the dependency and re-enable relevant test cases. Find them by grepping for this issue number.

**Comment by boris-petrov** [comment]
@f4lco - [Jersey 3.0.0 preview is out](https://projects.eclipse.org/projects/ee4j.jersey/releases/3.0.0) (I guess it has been "jakarta-ified"). Would you mind setting this version in the `gretty4` branch and enabling back the tests so that we check if all is fine? Hopefully these simple changes will be enough. If something breaks, we can dig in. Thanks!

**Comment by boris-petrov** [comment]
Not sure why GitHub didn't close the issue automatically but this is now fixed, thanks to @f4lco!
