### ISSUE TITLE
Jakarta migration

### ISSUE THREAD

**Issue by davidribeirofhp** [gretty-gradle-plugin/gretty#239]
I am migrating all my software to the latest version of gretty and Tomcat, but I depend on a library that doesn't support jakarta yet. I found a migration tool by tomcat that can do this successfully: either as an ant task (https://github.com/apache/tomcat-jakartaee-migration) or on Tomcat itself by deploying the webapp in the webapps-javaee directory (or by including a special loader entry on the context.xml).
However I cannot get any of these approaches to work with gretty, is this supported somehow?

**Comment by boris-petrov** [comment]
@davidribeirofhp - I'm not sure I understood exactly your problem. Gretty supports Jakarta containers from version 4.0.0. You should try that and let us know if you have any troubles with it.

**Comment by davidribeirofhp** [comment]
I found the source for the solution using the context.xml: https://stackoverflow.com/a/66805452 I added that loader line to the context.xml and it works on tomcat. When running with Gretty it complains of missing classes.

**Comment by f4lco** [comment]
I think that invoking the Jakarta conversion Ant task prior to running Gretty is about setting up some task dependencies in the build script of the application. If specific questions about the Gretty's task or behavior exist, we'd gladly answer them.

The Tomcat configuration example from https://stackoverflow.com/a/66805452 should work, though. Given that is a valid configuration of Tomcat, that should work in Gretty, too.
@davidribeirofhp could you cobble together a reproducer project and share a link to its repo? That would help immensely, because we would see what you have tried, we could use that to debug Gretty, and finally even convert that into a test case to prevent future regressions.

**Comment by f4lco** [comment]
Hello @davidribeirofhp, sorry for the delay, I've been on vacation. Thank you very much for the reproducer, this has been immensely helpful. My current understanding is: First, Gretty needs a small patch to avoid spamming the log. Second, I'm sorry to say that your use-case may go unaddressed, and the way I see it, the solution is beyond the scope of Gretty.

I think what's blocking you from the adoption of Jakarta EE is the use of the `KeycloakOIDCFilter`, which is from a library (dependency) that has not yet migrated. Whenever I say `KeycloakOIDCFilter`, that's really a placeholder for any dependency which did not yet adopt the renamed APIs.

Then we have two options:

### Ant Task

The Ant task is a build-time task to rewrite the imports from the `javax`prefix to `jakarta`. This might work for your use case and is probably your best option going forward. The Ant task may analyze your webapp as well as the dependencies and produce a new WAR which only depends on the Jakarta APIs. If you have any specific questions regarding the task setup or the behavior of Gretty, please ask.

### Loader / Transformer

The loader / transformer approach performs the migration on-the-fly when booting the webapp. The transformer is activated in the Tomcat context configuration:

```
<Context>
    <Loader jakartaConverter="TOMCAT" />
</Context>
```

I don't think the loader / transformer approach will work for third-party dependencies relying on `javax` classes. Consider the following method from Tomcat:

https://github.com/apache/tomcat/blob/e28fdd3e611ac7c057eda906570ee0cb61542e56/java/org/apache/catalina/loader/WebappClassLoaderBase.java#L2367-L2384

The `ClassFileTransformers`only come into play if we can fetch the resource from the webapp classloader: `resources.getClassLoaderResource(path)`, which resolves to `getResource("/WEB-INF/classes" + path, true, true)`, otherwise we have an early exit and delegate to the parent classloader. So at this time, Tomcat is taking 'webapp classpath' quite literally, it's the path of the classes of the webapp, and does not include the libraries in `WEB-INF/lib`, for example. That's the reason why the rewriting to Jakarta does not affect the `KeycloakOIDCFilter`, because it does not live within `/WEB-INF/classes`. 


### Conclusion

I would wait for the dependencies to adopt the Jakarta APIs - there is always risk in rewriting the code of dependencies which you do not control or can exhaustively review. I mean, the migration tool can rewrite the imports, but not all the string references reaching for the javax APIs. Eventually, the dependency might not work as you expect.
Once the dependencies are in place, I would think the loader / transformer approach is the way to go. The way I understand it, the transformer would let you gradually migrate the classes of the webapp to the Jakarta APIs.

**For Gretty**, we have the following work items:
- [ ] prevent log spam from the JAR scanner scanning `jakartaee-migration-1.0.0.jar`
- [ ] convert the reproducer and include an integration test that checks if we can run a javax webapp within Tomcat with the `jakartaConverter`context configuration

**Comment by davidribeirofhp** [comment]
Hi @f4lco no problem at all, welcome back :) I agree these approaches have some associated risk. In my case, this is the only dependency causing problems, I think it would work.

### Ant Task

I'd be interested in using gretty's apprun task with its auto reload feature. This ant task takes a war as input and outputs the transformed war. Do you see a way to plug it in gretty's tasks? Maybe adding as a dependency of a task? I don't know gretty's internals, does it use a war at some point?

### Loader / Transformer

This approach works in tomcat, in my previous comment I included a command to run a tomcat instance in docker container to run the war. It works because it is running a war? Does gretty use a different approach?

When I tried running with gretty it complained of missing classes from the jakartaee-migration lib. For some reason, it is not shipped with the tomcat instance used by gretty. So I tried including the lib as a gretty dependency in build.gradle:
```gradle
gretty group: 'org.apache.tomcat', name: 'jakartaee-migration', version: '1.0.0'
```
I have the impression that this is not working correctly either, in the logs there are errors like this:
```bash
Caused by: java.nio.file.NoSuchFileException: /Users/david.ribeiro/.gradle/caches/modules-2/files-2.1/org.apache.tomcat/jakartaee-migration/1.0.0/918eb0a9708431b1c1ce2d9a58e9590d9a8f694b/bcel-6.5.0.jar
```
It seems to me it is looking for jakartaee-migration's dependencies in a wrong directory, does it seem the same to you?

**Comment by davidribeirofhp** [comment]
Hi again, I found out the answer to my first question, running appRunWar instead of appRun builds the war and runs it. In the sample project, the ant task is already triggered and it works (if we delete the context.xml and unnecessary gretty dependency).
Would you mind just checking the Loader /Transformer question? There may be a problem with declaring gretty dependencies.

**Comment by f4lco** [comment]
@davidribeirofhp that's good news! For running the WAR, we also have the `inplace` toggle. With `inplace = false` Gretty also packages and deploys the WAR file instead of serving straight from the file system.

For the loader/transformer thing, please take a look at my pending PR #242! The PR includes an example project (which I derived from your reproducer), and a README detailing the approach (basically a tutorial on how to set up a project still using `javax`), and a small patch to Gretty. I hope we release that soon.

> It works because it is running a war? 

Yes, to my understanding, this is the case, because the loader / transformer approach only looks at the contents of `WEB-INF/classes`, a directory typically found within a WAR.

> When I tried running with gretty it complained of missing classes from the jakartaee-migration lib

My take-aways from analysing the reproducer have been the following:

- The best dependency scope for the migration lib is probably `grettyRunnerTomcat10`. Because that dependency configuration is tied to the runner, and a specific Tomcat version, it is probably the best fit for the migration lib.
- The `NoSuchFileException`you are seeing is just log spam. In my experiments, Gretty still works as expected even if you see that on the console. The PR #242 contains a fix for Gretty to fix that output.

**Comment by davidribeirofhp** [comment]
@f4lco great! Thank you for your help, I guess I can close the issue then
