### ISSUE TITLE
Gretty ignoring the JDK set from the Toolchain

### ISSUE THREAD

**Issue by mdeinum** [gretty-gradle-plugin/gretty#261]
With Gradle you can specify a Java Toolchain to use a certain JDK. Currenty I'm developing for JDK19, although Gradle itself doesn't run (yet) on JDK 19, I can specify a toolchain to point to Java 19 and have my classes compiled and tested with it. 

However when using Gretty to launch tomcat that same JDK isn't honoured and falls back to JDK17. Which ofcourse will lead to issues with class compatiblity. 

It would be nice if Gretty would take the selected toolchain into consideration when running the server.

**Comment by f4lco** [comment]
I agree, it would be nice to have toolchain support. Do you think you can prepare a patch yourself and do a PR? I would gladly review a patch and help out with a new release.
By the way, are you on 3.x or 4.x?

**Comment by mdeinum** [comment]
I would need to dig into the plugin and it would be my first gradle thing, but I can have a go. 

It took me a while to figure out that I'm on 4 and not on 3. the documentation is still for version 3 and not 4 so it is a bit strange.

**Comment by f4lco** [comment]
Cool @mdeinum! This is definitely an opportunity to learn.

> I would need to dig into the plugin and it would be my first gradle thing, but I can have a go.

In case you get stuck, please ask for help/guidance on Gitter/Matrix (find the link on the front page in the README, labeled "chat on gitter") 👍 

> It took me a while to figure out that I'm on 4 and not on 3. the documentation is still for version 3 and not 4 so it is a bit strange.

Yes, the Gretty docs could improve on that 🙈 
At this time, we support both Gretty 3.x and 4.x. Only the list of supported servlet containers differs, "old" servlet containers (Tomcat and Jetty below 10.x) go into Gretty 3.x, and Gretty 4.x picks up the more recent servlet container releases.
Regarding your patch, because the patch will not depend on a particular servlet container, we can port it freely between the two Gretty versions.

**Comment by boris-petrov** [comment]
I believe this issue has been resolved in both 3.x and 4.x thanks to @mr-serjey!
