### ISSUE TITLE
Wrong warning about missing slf4j provider

### ISSUE THREAD

**Issue by ArLau** [gretty-gradle-plugin/gretty#275]
Gretty 3.1.0 supports slf4j 2.x, but still checks for `log4j-slf4j-impl` in https://github.com/gretty-gradle-plugin/gretty/blob/c7f04337ee497e6b05e6d5d240ac4f271dc43dc1/libs/gretty/src/main/groovy/org/akhikhl/gretty/GrettyPlugin.groovy#L128-L133. For slf4j 2.x `log4j-slf4j2-impl` is a valid provider, but will cause Gretty to log a warning about missing slf4j provider (`Found slf4j-api dependency but no providers were found.  Did you mean to add slf4j-simple? See https://www.slf4j.org/codes.html#noProviders .`)

Maybe the check is not needed anymore as slf4j seems to log a warning in case the provider is missing?

**Comment by f4lco** [comment]
Yes, this is very likely a bug, because:
- slf4j does log this warning on its own - no need to replicate that warning in Gretty
- Gretty should / does not know about an exhaustive list of slf4j implementations, and thus will generate some false-positives.

Let's look at the commit history on that warning, and probably drop the warning message.

Thank you for your report, @ArLau!
