### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by henrik242** [gretty-gradle-plugin/gretty#8]
Barring some documentation updates, I believe the current master is fairly ready for a release. I'm using approximately the same build in production, and it has solved the jdk9, gradle and spring related problems that I had with 2.0.0.

Is anything else missing?

**Edit**

List of potential release-blockers:

* ~~#13 JDK9 simple smoke-test fails during logback initialization~~
* ~~#15 JDK9 cannot complete testAll: Jasper Source option 1.5 is no longer supported. Use 1.6 or later.~~
* #23 JDK9 Jasper/JSPC for Jetty 9.4.8.v20171121 is not fully JDK9-ready

**Comment by javabrett** [comment]
Yes an early release is a good idea and I agree it shouldn't be far from reach.  I would like to do some more JDK9 testing - I am getting a failure in a basic smoke-test application, but it sounds like you are having some success with JDK9.  I will raise an issue once I have more details, and try an work out why it doesn't trigger a test-failure.

> I'm using approximately the same build in production

Approximate because you are building it yourself from source, or from another branch - do you have additional patches you need added?  What would it take to move to loading from say https://raw.githubusercontent.com/gretty-gradle-plugin/gretty/master/pluginScripts/gretty-SNAPSHOT.plugin (or some release or RC)?  That's what I'm hoping to do for a couple of projects for further testing.

I'd like to get https://github.com/akhikhl/gretty/pull/395 reviewed then I will merge it.

Given this is the first release on this fork it is likely some things may go wrong, as I don't have a release process.  Gradle does most of the work, but I need to set-up my signing-keys etc. and that is the most likely place to fail.  If we need 2.1.0 to be a good/clean/first release, then maybe testing the release procedure with an RC1 would be worthwhile?

And yes someone will need to get around to the minimal set of doc-changes.

**Comment by henrik242** [comment]
An RC is an excellent idea. The version I'm using now is built from https://github.com/henrik242/gretty/tree/finn   

I'll try using this branch instead, but it'll have to wait till I get back to my computer  tomorrow.

**Comment by henrik242** [comment]
I tried the latest from here (commit  90f3ae4) in my build, it works flawlessly.  I use jdk9 and tomcat 8.5.28.  Can we cut an RC?

**Comment by henrik242** [comment]
(Even though there are some resolved issues, it might be easier for people to verify gretty locally if an RC is available)

**Comment by javabrett** [comment]
@henrik242 agreed, I will start on that task.

**Comment by henrik242** [comment]
@javabrett By the way, do you know why the gretty plugin uses `gradle.plugin.org.akhikhl.gretty` (instead of just `org.akhikhl.gretty`.  The former seems unnecessary to me, but there is possibly some requirements that I'm not aware of?  E.g. spring-boot-gradle-plugin (and many others) doesn't use the `gradle.plugin.org` prefix.

Ref. https://plugins.gradle.org/plugin/org.akhikhl.gretty

**Comment by wolfs** [comment]
For an explanation why `gradle.plugin` is prefixed to the group see here: https://plugins.gradle.org/docs/publish-plugin

**Comment by henrik242** [comment]
Thanks!  I think I prefer the non-default version (like [spring-boot](https://plugins.gradle.org/plugin/org.springframework.boot)):

> If you would like to have a non-prefixed coordinate group, you can do so by setting the group in a mavenCoordinates block. Note that non-prefixed groups require manual approval the first time one is published.

**Comment by javabrett** [comment]
**Update**: I have nearly finished a wrestle with Bintray signing API, so getting closer.  I notice a bunch of enhancements rolled-in recently from @boris-petrov , thanks!

If I gain some more confidence in the release process over the weekend, we might be able to skip the RC and just release 2.1.0 ... can always follow-up with a 2.1.1.

**Comment by henrik242** [comment]
@javabrett Nice work!

**Comment by javabrett** [comment]
If I don't hear any -1s here between now and tomorrow, I plan to release then.

**Comment by javabrett** [comment]
```
$ git show v2.1.0
tag v2.1.0
Tagger: Brett Randall <javabrett@gmail.com>
Date:   Tue Mar 13 10:10:44 2018 +1100

release 2.1.0 (gretty.org)
-----BEGIN PGP SIGNATURE-----

iQIzBAABCAAdFiEEJY/+CLLdUH9Q9kG1UO+LC3wEsp0FAlqnCPQACgkQUO+LC3wE
sp1CVBAApzLBaIv3lJ3bhcVONfV4Kegiuwoc3ewX2boc/Ew+ike4INloamgQesc/
4n5BVb+WbiEyorUS+DxaPm6Jx1ZQHGGirwqKP3T/dFxlqCz5MJ/KCZwNdwA6qHpt
gbTVDboM60STEU7iagynu4ng/bGv2VO+YTgcoM+pg6f6wLnkXhqCLmjl+LVV7qk3
KeEJK9XDJsvHcIo3L9YI4BMwo2BH3TvQdi5x7W7XB5YZjFIoCDg9SerzDNo8EYO0
HBTyhLlpDAJuCBGWw9n5oO7TK7q8fo/TVIKPRw3dvUKvo8OoEk1Q70pH82USriA1
D09vS69Rzk4NSaYKxO2OFJaAasOMXUfkdtttIJUkMGF003SRar4nM7naYF7CXEF4
mKjq4edkdcxQj+Ze2iKbAzAUkXVohg995V9bOp/5yJKkz4XNsvHqE9CuKongcwk+
Bi21w00SgtD76eIWQ5SK7BiJjRpq1DELpbCb4uDjHy8rivXAk8tDFBAYVBymYmkR
U8vKCkSfA5zBa7meDc9ooZhNihaMMU4mpgcLgEz8fEiB06z5QmxcJvFnswDJMHeY
Cazat0CIfR3rQJwem6nhRDIGQGWZ3PyN5TjONtwoQF0XA475vwydcx3WtKSvLX+B
6BcO/+ARAmzndMSkhxas3HvwH2cEegeySARUC0Y7PC00hJN3Xdk=
=i409
-----END PGP SIGNATURE-----

commit fe063a3c2a99afdb90f3865000aaae5ae263ca52 (HEAD -> master, tag: v2.1.0, upstream/master)
Author: Brett Randall <javabrett@gmail.com>
Date:   Mon Mar 12 11:43:22 2018 +1100

    release 2.1.0 (gretty.org)
    
    Signed-off-by: Brett Randall <javabrett@gmail.com>
```

**Comment by henrik242** [comment]
@javabrett Nice work!
